from __future__ import annotations

from typing import Protocol

from backend.app.domain.models import (
    AgentMessage,
    AuditEvent,
    ImpactSummary,
    MemoryRecord,
    StoredUser,
    TaskRecord,
    ToolExecution,
    WorkflowRun,
)


class AppRepository(Protocol):
    async def create_user(self, user: StoredUser) -> StoredUser: ...

    async def get_user_by_email(self, email: str) -> StoredUser | None: ...

    async def get_user_by_id(self, user_id: str) -> StoredUser | None: ...

    async def save_task(self, task: TaskRecord) -> TaskRecord: ...

    async def get_task(self, task_id: str) -> TaskRecord | None: ...

    async def save_workflow_run(self, run: WorkflowRun) -> WorkflowRun: ...

    async def get_workflow_run(self, run_id: str) -> WorkflowRun | None: ...

    async def save_agent_message(self, message: AgentMessage) -> AgentMessage: ...

    async def list_agent_messages(self, task_id: str) -> list[AgentMessage]: ...

    async def save_tool_execution(self, execution: ToolExecution) -> ToolExecution: ...

    async def list_tool_executions(self, task_id: str) -> list[ToolExecution]: ...

    async def save_memory(self, memory: MemoryRecord) -> MemoryRecord: ...

    async def list_memories(self, task_id: str | None = None) -> list[MemoryRecord]: ...

    async def save_audit_event(self, event: AuditEvent) -> AuditEvent: ...

    async def list_audit_events(self, resource_id: str | None = None) -> list[AuditEvent]: ...

    async def set_simulated_score(self, lake_id: str, score: int) -> None: ...

    async def get_simulated_score(self, lake_id: str) -> int | None: ...


class GraphRepository(Protocol):
    async def health_check(self) -> dict[str, object]: ...

    async def get_impact(self, lake_id: str) -> ImpactSummary | None: ...
