// VAJRAWATCH — Lake Registry
// 47 glacial lakes: coordinates + metadata ONLY
// No risk scores, no tiers, no generated values
// Risk data comes exclusively from backend /api/analyze/:id

export const LAKES = [
  // ── NEPAL (21) ──────────────────────────────────────────────────────────
  {
    id: "NP-001",
    name: "Thulagi Lake",
    lat: 28.5,
    lng: 84.68,
    country: "Nepal",
    region: "Manaslu",
  },
  {
    id: "NP-002",
    name: "Imja Tsho",
    lat: 27.9,
    lng: 86.92,
    country: "Nepal",
    region: "Khumbu",
  },
  {
    id: "NP-003",
    name: "Lower Barun Lake",
    lat: 27.82,
    lng: 87.11,
    country: "Nepal",
    region: "Makalu",
  },
  {
    id: "NP-004",
    name: "Tsho Rolpa",
    lat: 27.88,
    lng: 86.48,
    country: "Nepal",
    region: "Rolwaling",
  },
  {
    id: "NP-005",
    name: "Dudh Pokhari",
    lat: 28.42,
    lng: 83.85,
    country: "Nepal",
    region: "Annapurna",
  },
  {
    id: "NP-006",
    name: "Sabai Tsho",
    lat: 27.92,
    lng: 86.58,
    country: "Nepal",
    region: "Rolwaling",
  },
  {
    id: "NP-007",
    name: "Chamlang South Tsho",
    lat: 27.8,
    lng: 87.16,
    country: "Nepal",
    region: "Makalu",
  },
  {
    id: "NP-008",
    name: "Dig Tsho",
    lat: 27.9,
    lng: 86.62,
    country: "Nepal",
    region: "Khumbu",
  },
  {
    id: "NP-009",
    name: "Lumding Tsho",
    lat: 27.85,
    lng: 86.9,
    country: "Nepal",
    region: "Khumbu",
  },
  {
    id: "NP-010",
    name: "Nagma Pokhari",
    lat: 28.68,
    lng: 84.48,
    country: "Nepal",
    region: "Manaslu",
  },
  {
    id: "NP-011",
    name: "Sankhuwasabha Lake",
    lat: 27.78,
    lng: 87.3,
    country: "Nepal",
    region: "Arun",
  },
  {
    id: "NP-012",
    name: "Mera Glacier Lake",
    lat: 27.72,
    lng: 86.86,
    country: "Nepal",
    region: "Hinku",
  },
  {
    id: "NP-013",
    name: "Lumsa Tsho",
    lat: 27.97,
    lng: 86.45,
    country: "Nepal",
    region: "Rolwaling",
  },
  {
    id: "NP-014",
    name: "Lower Barun 2",
    lat: 27.85,
    lng: 87.08,
    country: "Nepal",
    region: "Makalu",
  },
  {
    id: "NP-015",
    name: "Chukhung Tsho",
    lat: 27.93,
    lng: 86.97,
    country: "Nepal",
    region: "Khumbu",
  },
  {
    id: "NP-016",
    name: "Langtang Lake",
    lat: 28.25,
    lng: 85.65,
    country: "Nepal",
    region: "Langtang",
  },
  {
    id: "NP-017",
    name: "Morimoto Lake",
    lat: 28.18,
    lng: 85.72,
    country: "Nepal",
    region: "Langtang",
  },
  {
    id: "NP-018",
    name: "Shalbachum Lake",
    lat: 28.2,
    lng: 85.6,
    country: "Nepal",
    region: "Langtang",
  },
  {
    id: "NP-019",
    name: "Ghunsa Lake",
    lat: 27.62,
    lng: 87.9,
    country: "Nepal",
    region: "Taplejung",
  },
  {
    id: "NP-020",
    name: "Sipsong Lake",
    lat: 28.05,
    lng: 86.72,
    country: "Nepal",
    region: "Solukhumbu",
  },
  {
    id: "NP-021",
    name: "Ngozumpa Tsho",
    lat: 28.0,
    lng: 86.68,
    country: "Nepal",
    region: "Khumbu",
  },

  // ── INDIA (1) ────────────────────────────────────────────────────────────
  {
    id: "IN-001",
    name: "South Lhonak Lake",
    lat: 27.72,
    lng: 88.18,
    country: "India",
    region: "Sikkim",
  },

  // ── TIBET / CHINA (25) ──────────────────────────────────────────────────
  {
    id: "CN-001",
    name: "Longbasaba Lake",
    lat: 28.22,
    lng: 88.08,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-002",
    name: "Pida Lake",
    lat: 28.42,
    lng: 88.02,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-003",
    name: "Galongla Lake",
    lat: 29.48,
    lng: 94.72,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-004",
    name: "Midui Lake",
    lat: 29.32,
    lng: 96.52,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-005",
    name: "Baqing Lake",
    lat: 30.42,
    lng: 97.68,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-006",
    name: "Ranwu Lake",
    lat: 29.48,
    lng: 96.78,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-007",
    name: "Yigong Lake",
    lat: 30.18,
    lng: 94.68,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-008",
    name: "Luozha Lake",
    lat: 28.12,
    lng: 90.68,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-009",
    name: "Cuonajiacuo",
    lat: 29.82,
    lng: 92.48,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-010",
    name: "Zepu Lake",
    lat: 30.62,
    lng: 91.28,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-011",
    name: "Jiongpu Lake",
    lat: 28.82,
    lng: 85.72,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-012",
    name: "Zonag Lake",
    lat: 29.18,
    lng: 86.48,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-013",
    name: "Pagsum Lake",
    lat: 29.72,
    lng: 93.18,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-014",
    name: "Siling Lake",
    lat: 31.82,
    lng: 89.02,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-015",
    name: "Dang Lake",
    lat: 30.52,
    lng: 86.88,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-016",
    name: "Taro Lake",
    lat: 31.12,
    lng: 83.48,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-017",
    name: "Jibu Lake",
    lat: 31.48,
    lng: 87.68,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-018",
    name: "Zhaxi Lake",
    lat: 30.78,
    lng: 84.28,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-019",
    name: "Wuru Lake",
    lat: 33.42,
    lng: 87.08,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-020",
    name: "Longmu Lake",
    lat: 35.58,
    lng: 80.12,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-021",
    name: "Lehuo Lake",
    lat: 32.12,
    lng: 86.48,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-022",
    name: "Baxiu Lake",
    lat: 29.88,
    lng: 94.22,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-023",
    name: "Cona Lake",
    lat: 28.18,
    lng: 91.68,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-024",
    name: "Jiali Lake",
    lat: 30.18,
    lng: 93.68,
    country: "China",
    region: "Tibet",
  },
  {
    id: "CN-025",
    name: "Luding Glacier Lake",
    lat: 28.68,
    lng: 92.38,
    country: "China",
    region: "Tibet",
  },
];

// Backend response contract — what /api/analyze/:id must return:
// {
//   score: number (0-100),
//   tier: "RED" | "ORANGE" | "YELLOW" | "GREEN",
//   action: { title: string, steps: string },
//   drivers: [{ name: string, pct: number, value: string, color: string }],
//   impact: { population: string, settlements: string, infrastructure: string, reach: string }
// }
